server {
    listen 80 casser;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    # Endpoint de health check (niveau 2)
    location /health {
        access_log off;
        default_type text/plain;
        return 200 "ok\n";
    }
}
